unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set -g base-index 1
set -g pane-base-index 1

set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n M-H previous-window
bind -n M-L next-window

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g default-terminal "tmux-256color"

# set -g @plugin 'Nybkox/tmux-kanagawa'
# set -g @kanagawa-ignore-window-colors true

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_directory 'on'
set -g @rose_pine_only_windows 'on'
set -g @rose_pine_current_window_icon ''

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run ~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux

# set -g status-right-length 100
# set -g status-left-length 100
# set -g status-left ""
#
# set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-right "#{E:@catppuccin_status_directory}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -g @catppuccin_window_default_text " #W"
# set -g @catppuccin_window_current_text " #W"
# set -g @catppuccin_window_text " #W"
#
# set -g @catppuccin_status_module_bg_color "#{@thm_surface_0}"
# set -g @catppuccin_window_current_color '#{E:@thm_crust}'

run '~/.tmux/plugins/tpm/tpm'
